//--------------------------------------------------------------
//  CSE 340 Project 2
//  Student Name: Daniel Martin
//  
//  Description: This library reads in tokens from stdin, and 
//  classifies them according to type.
//--------------------------------------------------------------

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "lexer.h"

#define RESERVED  5

char token[MAX_TOKEN_LENGTH];
int  tokenLength;
int  ttype;
int  line = 1;

static int active_token = 0;
static char *reserved[] =
	{	"",
		"ID",
        "#",
        "##",
        "->",
		"ERROR"
	};


static void skip_space()
{
	char c;

	c = getchar();
	line += (c == '\n');
	while (!feof(stdin) && isspace(c))
	{
		c = getchar();
        line += (c == '\n');
	}
	// return character to input buffer if eof is not reached
	if (!feof(stdin))
		ungetc(c,stdin);
}


static int scan_id()
{
	char c;

	c = getchar();
	if (isalpha(c))
	{
		while (isalnum(c) && tokenLength < MAX_TOKEN_LENGTH)
		{
			token[tokenLength] = c;
			tokenLength++;
			c = getchar();
		}
		token[tokenLength] = '\0';
		ungetc(c, stdin);
		return ID;
	}
	else
		return ERROR;
}

int getToken()
{
	char c;

	if (active_token)
	{
		active_token = 0;
		return ttype;
	}
	skip_space();
	tokenLength = 0;
	token[0] = '\0';
	c = getchar();
	switch (c)
	{
       case '#':
			c = getchar();
			if (c == '#')
				ttype = DOUBLEHASH;
			else
			{
				ungetc(c, stdin);
				ttype = HASH;
			}
			return ttype;
       case '-':
			c = getchar();
			if (c == '>')
				ttype = ARROW;
			else
			{
				ungetc(c, stdin);
				ttype = ERROR;
			}
			return ttype;
       default :
			if (isalpha(c)) // ID must begin with a letter
			{
				ungetc(c, stdin);
				ttype = scan_id();
			}
			else if (c == EOF)
			{
				ttype = EOF;
			}
			else
			{
				ttype = ERROR;
			}
			return ttype;
	}
}

void ungetToken()
{
	active_token = 1;
}

/*
 * Write your code in a separate file, do NOT edit this file.
 *
 *
 *
 * If using C, include lexer.h in your C code and compile and
 * link your code with lexer.c like this:
 *
 * $ gcc -Wall lexer.c your_file.c
 *
 *
 *
 * If using C++, include lexer.h like this in your C++ code:
 *
 * extern "C" {
 *     #include "lexer.h"
 * }
 *
 * And compile and link the C and C++ code like this:
 *
 * $ gcc -Wall -c lexer.c
 * $ g++ -Wall lexer.o your_file.cpp
 *
 * The first command just compiles the C code. The second 
 * command compiles your C++ code and links it with the 
 * compiled lexer.
 *
 */

